/**
 * The nine founder failures rendered on `/socials`.
 *
 * The rail on `/socials` shows one ball per failure in this order (the centre
 * of the sequence is the visually largest ball). Each entry also drives its own
 * `/socials/<slug>` deep-dive page, whose artwork lives in `public/socials/`
 * and is generated by `scripts/generate-failure-art.mjs`.
 */

export type FailureFrame = {
  /** File name (without extension) inside `public/socials/`. */
  frame: string;
  caption: string;
};

export type FailureStage = {
  when: string;
  what: string;
};

export type FailureRemedy = {
  /** The Altitut surface that intercepts this failure. */
  surface: string;
  how: string;
};

export type Failure = {
  slug: string;
  /** Two-word label printed inside the ball. */
  label: string;
  /** Short kicker under the ball label. */
  kicker: string;
  /** Full failure name used as the page title. */
  title: string;
  /** One-line verdict. */
  verdict: string;
  /** Punch-in-the-gut stat, shown large. */
  stat: string;
  statNote: string;
  /** The emotional opening of the deep-dive page. */
  opening: string[];
  /** What the founder tells themselves while it happens. */
  lie: string;
  /** How it actually ends. */
  ending: string;
  /** The slow-motion anatomy of the failure. */
  anatomy: FailureStage[];
  /** How Altitut intercepts it, mapped to real product surfaces. */
  remedies: FailureRemedy[];
  /** The one sentence that reframes the failure. */
  reframe: string;
  /**
   * The three "failure side" frames shown in the narrative. The hero, resolution
   * and horizon frames (`<slug>-hero`, `<slug>-resolution`, `<slug>-horizon`)
   * are derived from the slug by the page itself.
   */
  images: FailureFrame[];
};

export const FAILURES: Failure[] = [
  {
    slug: "building-for-nobody",
    label: "Building\nfor nobody",
    kicker: "No customer ever asked",
    title: "Building for nobody",
    verdict:
      "You shipped for eleven months and the only person who ever needed it was you.",
    stat: "42%",
    statNote:
      "of startups die because there was no market need — the single most common cause of failure.",
    opening: [
      "It starts as certainty. You can see the product so clearly that talking to strangers feels like a detour — a tax on momentum.",
      "So you build. You name it. You buy the domain. You tell your parents. And every week the thing in your head gets more detailed and the world outside it stays exactly as quiet as it was on day one.",
      "The failure is not that nobody wanted it. The failure is that you could have known in nine days instead of nine months.",
    ],
    lie: "\u201cI'll talk to users once there's something to show them.\u201d",
    ending:
      "Launch day arrives. Forty-one visitors. Two signups, both friends. The silence is louder than any rejection.",
    anatomy: [
      { when: "Week 1", what: "A conviction arrives, fully formed and unexamined." },
      { when: "Week 3", what: "Scope grows to protect the idea from being tested." },
      { when: "Month 3", what: "Feedback is postponed until \u201cit's ready\u201d." },
      { when: "Month 9", what: "Launch. The market answers with silence." },
    ],
    remedies: [
      {
        surface: "Interviews hub",
        how: "Every hypothesis you hold is written down before you build, then linked to real interviews. Altitut plans the questions, records the call, transcribes it, extracts insights and tells you which hypothesis just survived and which just died.",
      },
      {
        surface: "Learning: Problem Discovery",
        how: "The curriculum gates progress on evidence, not effort. Sessions on hypotheses and interviewing stay locked until real conversations exist in your account.",
      },
      {
        surface: "Personas: Customer Discovery",
        how: "Interview data compounds into personas with fit scoring, so \u201cwho is this for\u201d stops being a guess and becomes a record.",
      },
    ],
    reframe:
      "Talking to ten humans is not slower than building. It is the only part that was ever fast.",
    images: [
      { frame: "building-for-nobody-failure", caption: "Nine months of work, radiating outward from an untested centre." },
      { frame: "building-for-nobody-network", caption: "The conversations that would have redirected you in week one." },
      { frame: "building-for-nobody-map", caption: "The market you assumed, contoured against the one that exists." },
    ],
  },
  {
    slug: "in-love-with-the-idea",
    label: "In love\nwith the idea",
    kicker: "Solution first, problem never",
    title: "In love with the idea",
    verdict:
      "You fell for your solution so hard that you started defending it against your own users.",
    stat: "1 in 3",
    statNote:
      "pivots that arrive too late are pivots founders privately admit they saw coming months earlier.",
    opening: [
      "There is a specific kind of heartbreak in entrepreneurship: the moment the idea you love stops being the idea that works, and you keep going anyway.",
      "You hear the objection in the third interview. You hear it again in the fifth. By the ninth you have a rebuttal ready before the sentence finishes — and that rebuttal is the sound of the company ending slowly.",
      "Loving an idea is not the failure. Refusing to let the idea be wrong is.",
    ],
    lie: "\u201cThey just don't get it yet.\u201d",
    ending:
      "Two years in, you pivot to what the very first user described — and someone else has already built it.",
    anatomy: [
      { when: "Interview 3", what: "The first real objection arrives. You explain it away." },
      { when: "Interview 9", what: "You start pre-answering objections instead of hearing them." },
      { when: "Month 8", what: "Your roadmap defends the idea rather than testing it." },
      { when: "Year 2", what: "The pivot you needed is now someone else's product." },
    ],
    remedies: [
      {
        surface: "Ikigai idea discovery",
        how: "Ideas are generated from the intersection of your passion, expertise, mission and market — with local market-trend analysis — so your attachment is to a direction, not a single fragile artefact.",
      },
      {
        surface: "Hypotheses tracking",
        how: "Beliefs are stated as falsifiable hypotheses with a validation state. When evidence kills one, the platform shows it as killed. There is nowhere for the flinch to hide.",
      },
      {
        surface: "Altitut Graveyard + Competitors matrix",
        how: "In My Startup you study failed startups and place yourself on a 2D positioning matrix — a weekly reminder that conviction without differentiation is just a longer runway to the same ending.",
      },
    ],
    reframe:
      "Be loyal to the problem. Ideas are disposable; the people with the problem are not.",
    images: [
      { frame: "in-love-with-the-idea-failure", caption: "One idea, protected from every angle of attack." },
      { frame: "in-love-with-the-idea-diagnosis", caption: "Signal you heard in week three, buried under your own noise." },
      { frame: "in-love-with-the-idea-system", caption: "Hypotheses as a grid: what survived, what you never checked." },
    ],
  },
  {
    slug: "the-invisible-pitch",
    label: "The invisible\npitch",
    kicker: "Real company, unhearable story",
    title: "The invisible pitch",
    verdict:
      "The work was real. The story was unhearable. Both of those facts killed it equally.",
    stat: "60 sec",
    statNote:
      "is roughly how long an investor, judge or customer listens before deciding whether to keep listening.",
    opening: [
      "You have built something genuinely good. Then you open your mouth and the first ninety seconds are architecture, integrations and a market-size slide nobody believes.",
      "The room nods politely. You leave knowing you did badly and not knowing which part was bad. Nobody in that room will ever tell you.",
      "This is the cruellest failure, because from the inside it feels like bad luck.",
    ],
    lie: "\u201cThe product speaks for itself.\u201d",
    ending:
      "Eleven applications, eleven rejections, zero feedback. You still cannot name the sentence that lost the room.",
    anatomy: [
      { when: "Slide 1", what: "You open with what it is instead of who is hurting." },
      { when: "Minute 2", what: "The stakes never land, so nothing after them matters." },
      { when: "Q&A", what: "You answer defensively; the room reads it as fragility." },
      { when: "After", what: "No feedback arrives, so the same pitch fails again next month." },
    ],
    remedies: [
      {
        surface: "Pitch \u2192 Review",
        how: "Upload the deck and get scored on clarity, structure, engagement and impact, slide by slide, with an explicit gap analysis. The feedback the room withheld, in writing.",
      },
      {
        surface: "Pitch \u2192 Craft",
        how: "A seven-section guided builder — Hook, Problem, Solution, Market, Model/Traction, Team, Ask — with templates, versioning and autosave, so the story has a spine instead of a vibe.",
      },
      {
        surface: "Pitch \u2192 Practice + Pitch Arena",
        how: "Record your delivery in-browser and get AI feedback on it, then perform it in the game's Demo Day arena. You fail in rehearsal, cheaply, over and over, instead of once in the room that mattered.",
      },
    ],
    reframe:
      "A pitch is not a summary of your work. It is the shortest path to making a stranger care.",
    images: [
      { frame: "the-invisible-pitch-diagnosis", caption: "Your signal, drowned under everything you also said." },
      { frame: "the-invisible-pitch-failure", caption: "Sixty seconds, fractured into sixty different messages." },
      { frame: "the-invisible-pitch-system", caption: "Seven sections. Each one either lands or it doesn't." },
    ],
  },
  {
    slug: "the-forever-mvp",
    label: "The forever\nMVP",
    kicker: "Always two weeks away",
    title: "The forever MVP",
    verdict:
      "The MVP has been two weeks away for fourteen months, because shipping it would end the fantasy.",
    stat: "14 mo",
    statNote:
      "is a common gap between \u201cwe started building\u201d and \u201csomeone outside the team used it\u201d.",
    opening: [
      "Building is the most comfortable place to hide. It is visibly productive, it never rejects you, and it postpones the only verdict that counts.",
      "So the login flow gets rebuilt. The design system arrives. There is a settings page nobody has asked for and an onboarding no user has seen.",
      "Every feature you add before contact with reality is a bet placed on a table you have not looked at.",
    ],
    lie: "\u201cIt's not ready to be seen yet.\u201d",
    ending:
      "The build is beautiful. The first ten users churn in a week over something you would have learned on day three.",
    anatomy: [
      { when: "Week 2", what: "Scope quietly widens to postpone judgement." },
      { when: "Month 4", what: "Infrastructure work replaces user contact entirely." },
      { when: "Month 9", what: "A redesign resets the finish line." },
      { when: "Month 14", what: "First real users. First real feedback. Most of the work was wrong." },
    ],
    remedies: [
      {
        surface: "MVP \u2192 Draw Product",
        how: "Sketch the screens; AI turns them into realistic mockups plus a PRD. You can put something testable in front of a human this afternoon instead of next quarter.",
      },
      {
        surface: "MVP \u2192 Prototype Builder & GitHub Workspace",
        how: "Clickable prototypes and a scaffolded repo mean the smallest honest version is always cheaper to build than the imaginary complete one.",
      },
      {
        surface: "Learning: MVP 101 \u2192 Testing & Iteration",
        how: "The curriculum ties building to a test loop, and Home tracks MVP projects against interviews, so a month of building with zero conversations shows up as the anomaly it is.",
      },
    ],
    reframe:
      "An MVP is not a small product. It is the fastest question you can ask reality.",
    images: [
      { frame: "the-forever-mvp-failure", caption: "Scope, radiating past the point of usefulness." },
      { frame: "the-forever-mvp-system", caption: "Everything you built. Shaded: what anyone used." },
      { frame: "the-forever-mvp-map", caption: "Fourteen months of contours around one unasked question." },
    ],
  },
  {
    slug: "runway-blindness",
    label: "Runway\nblindness",
    kicker: "Out of money, mid-sentence",
    title: "Runway blindness",
    verdict:
      "The company did not fail on strategy. It ran out of money in the middle of a sentence.",
    stat: "29%",
    statNote:
      "of startups fail simply because they ran out of cash — usually while the plan was still working.",
    opening: [
      "Nobody feels a runway ending. That is what makes it lethal. Spend happens in small justifiable pieces: a subscription, a contractor, a conference, a logo.",
      "Then one Tuesday you open the account and there are seven weeks left, and every option that could have saved you needed twelve.",
      "The money did not disappear. It was spent on things that felt like progress.",
    ],
    lie: "\u201cWe'll figure out revenue after launch.\u201d",
    ending:
      "You shut down with the product working, the users happy and the account empty.",
    anatomy: [
      { when: "Month 1", what: "Spend starts as a series of small, defensible yeses." },
      { when: "Month 5", what: "Burn is estimated from memory instead of measured." },
      { when: "Month 10", what: "Revenue is still a future tense." },
      { when: "Month 12", what: "Seven weeks of runway; every rescue needs twelve." },
    ],
    remedies: [
      {
        surface: "The Vault (Altitut Game)",
        how: "A financial-management world where you triage real startup expenses into Essential / Nice-to-have / Cut-it inside a fixed budget. You rehearse the cut before it costs you the company.",
      },
      {
        surface: "Personas \u2192 Pricing Discovery",
        how: "Willingness-to-pay and pricing analysis grounded in your own interview data, so revenue is designed alongside the product rather than after it.",
      },
      {
        surface: "Funding + Free Resources",
        how: "Deadline-sorted grants, competitions and free resources with application tracking, so non-dilutive money is found months before you need it, not seven weeks after.",
      },
    ],
    reframe:
      "Runway is not a number in a spreadsheet. It is how many questions you still get to ask.",
    images: [
      { frame: "runway-blindness-diagnosis", caption: "Burn: smooth, unremarkable, and then over." },
      { frame: "runway-blindness-failure", caption: "The same budget, split across everything that felt urgent." },
      { frame: "runway-blindness-system", caption: "Essential. Nice-to-have. Cut it. Decided in advance." },
    ],
  },
  {
    slug: "the-lonely-founder",
    label: "The lonely\nfounder",
    kicker: "Nobody to ask, nobody to tell",
    title: "The lonely founder",
    verdict:
      "Every decision was made alone, and the ones that were wrong stayed wrong for months.",
    stat: "0",
    statNote:
      "is how many people most first-time founders can call at 11pm about a decision that scares them.",
    opening: [
      "There is no meeting where founders admit they have nobody to ask. It leaks out differently: decisions deferred, obvious mistakes held for a year, wins that arrive strangely flat.",
      "Isolation does not just feel bad. It is mechanically expensive — you pay full price for every lesson someone else already paid for.",
      "Nobody drops out of entrepreneurship because it was hard. They drop out because it was hard alone.",
    ],
    lie: "\u201cI should be able to figure this out myself.\u201d",
    ending:
      "You quit in a week where nothing dramatic happened. There was simply nobody there when it got quiet.",
    anatomy: [
      { when: "Week 2", what: "The first scary decision is made alone, at midnight." },
      { when: "Month 3", what: "A fixable mistake sets and hardens for lack of a second opinion." },
      { when: "Month 6", what: "Wins stop registering; there is nobody to tell." },
      { when: "Month 8", what: "You stop, on an ordinary Tuesday, quietly." },
    ],
    remedies: [
      {
        surface: "Alti, the AI mentor",
        how: "An always-available mentor inside both the web app and the game, grounded in your actual startup data — so the 11pm question gets a real answer instead of another open tab.",
      },
      {
        surface: "Course, class chat & cohorts",
        how: "Join a class with an instructor code and you get sessions, assignments, feedback, a gradebook and classmates in the same week of the same journey. Structure replaces willpower.",
      },
      {
        surface: "Startup City & team collaboration",
        how: "Startup City, the Bit Bar and the arena make peers visible and social; team IDs, invitations and real-time multi-editor sync mean the work itself stops being a solo activity.",
      },
    ],
    reframe:
      "Founders do not need more grit. They need somebody who has seen this exact week before.",
    images: [
      { frame: "the-lonely-founder-failure", caption: "One centre, no edges reaching it." },
      { frame: "the-lonely-founder-network", caption: "The cohort you were always one message away from." },
      { frame: "the-lonely-founder-diagnosis", caption: "Months of signal nobody was listening to." },
    ],
  },
  {
    slug: "chasing-cheques",
    label: "Chasing\ncheques",
    kicker: "Funding instead of proof",
    title: "Chasing cheques",
    verdict:
      "You spent the year applying for money instead of earning the proof that money follows.",
    stat: "1%",
    statNote:
      "or worse is the acceptance rate of the competitions and grants most founders apply to blind.",
    opening: [
      "Applications feel like progress. They have deadlines, forms, word limits — all the texture of real work, and none of the risk of a customer saying no.",
      "So you write the same story forty times, tuned to nothing, aimed at everyone. Forty rejections arrive without a single line of explanation.",
      "Meanwhile the traction that would have made those forms trivial went unbuilt.",
    ],
    lie: "\u201cOnce we're funded, we can really start.\u201d",
    ending:
      "Forty submissions. Two shortlists. No cheque, no product, no evidence — and the year is gone.",
    anatomy: [
      { when: "Month 1", what: "You apply broadly, matched to nothing." },
      { when: "Month 4", what: "The same generic story is reused for every programme." },
      { when: "Month 7", what: "Rejections arrive with no reasons attached." },
      { when: "Month 12", what: "No funding, and no traction either." },
    ],
    remedies: [
      {
        surface: "Funding \u2192 match scores",
        how: "Competitions and grants are scored against your actual startup with eligibility filters, so you apply to the handful you can genuinely win instead of the hundred you cannot.",
      },
      {
        surface: "Integrated application flow",
        how: "Applications reuse your master pitch with AI-assisted answers, and tracking shows Available / Applied / Received — the admin cost of a serious application drops to near zero.",
      },
      {
        surface: "Badges & verifiable credentials",
        how: "Completed work produces publicly verifiable Block Certificates and a published startup profile — third-party proof, so the cheque follows evidence instead of the other way round.",
      },
    ],
    reframe:
      "Funding is a lagging indicator. Build the thing it lags behind.",
    images: [
      { frame: "chasing-cheques-failure", caption: "Forty applications, radiating from nothing." },
      { frame: "chasing-cheques-system", caption: "Eligibility, honestly assessed: most doors were never open." },
      { frame: "chasing-cheques-map", caption: "The few programmes actually shaped like your startup." },
    ],
  },
  {
    slug: "vanity-metrics",
    label: "Vanity\nmetrics",
    kicker: "Winning at the wrong number",
    title: "Vanity metrics",
    verdict:
      "Every chart went up and to the right, and not one of them was load-bearing.",
    stat: "0%",
    statNote:
      "week-four retention behind a graph that only ever showed signups going up.",
    opening: [
      "Vanity metrics are the most humane form of self-deception. Followers, signups, waitlist size, impressions — all real numbers, all technically true, none of them evidence that anyone came back.",
      "You optimise for what makes you feel like a founder. The dashboard rewards you. Retention quietly flatlines underneath.",
      "The tragedy is the effort was real. It was just pointed at a number that could not save you.",
    ],
    lie: "\u201cLook how fast we're growing.\u201d",
    ending:
      "Ten thousand signups, forty weekly actives, and a growth deck that no longer means anything.",
    anatomy: [
      { when: "Week 1", what: "You pick the metric that is easiest to move." },
      { when: "Month 2", what: "The chart goes up; the questions stop." },
      { when: "Month 5", what: "Retention is never measured, so it is never fixed." },
      { when: "Month 8", what: "Growth stalls and there is no instrument to explain why." },
    ],
    remedies: [
      {
        surface: "Home: Mission Control",
        how: "Your dashboard counts interviews completed, hypotheses validated, pitch recordings, MVP projects and personas — inputs that predict survival, not applause.",
      },
      {
        surface: "Learning: Scoreboard & Metrics",
        how: "A dedicated curriculum block on choosing metrics that can falsify your plan, plus retention and testing loops in Testing & Iteration.",
      },
      {
        surface: "Startup analytics & profile insights",
        how: "Your published startup profile reports real engagement, so the numbers you show the world are the same ones you steer by.",
      },
    ],
    reframe:
      "A real metric is one that can tell you that you are wrong.",
    images: [
      { frame: "vanity-metrics-diagnosis", caption: "Every line rising. None of them retention." },
      { frame: "vanity-metrics-failure", caption: "A dashboard fractured into numbers that cannot be acted on." },
      { frame: "vanity-metrics-map", caption: "The signal, once you contour it against behaviour." },
    ],
  },
  {
    slug: "the-quiet-quit",
    label: "The quiet\nquit",
    kicker: "Not a crash. A fade.",
    title: "The quiet quit",
    verdict:
      "Most startups do not explode. They go three weeks without being opened, and then it is over.",
    stat: "3 weeks",
    statNote:
      "of no meaningful progress is the point where most early startups silently stop for good.",
    opening: [
      "This is the failure nobody posts about. There is no dramatic collapse, no cautionary tale, no lesson learned in public.",
      "There is a week with an exam. Then a week where the momentum is gone and opening the file feels heavy. Then a month. Then it becomes a thing you used to be doing.",
      "You were not lazy. You were unsupported, unmeasured, and alone with an open-ended task and no next step small enough to take.",
    ],
    lie: "\u201cI'll pick it back up next week.\u201d",
    ending:
      "You never decide to stop. You just never start again — and you carry it for years.",
    anatomy: [
      { when: "Week 6", what: "A busy week breaks the streak." },
      { when: "Week 8", what: "The next step is too vague to begin." },
      { when: "Week 10", what: "Nobody notices you have stopped." },
      { when: "Month 4", what: "It becomes something you used to do." },
    ],
    remedies: [
      {
        surface: "Streaks, activity calendar & deadlines",
        how: "Home shows an activity calendar with streaks, deadline markers and a competition countdown, so a broken week is visible while it is still one week.",
      },
      {
        surface: "Learning modules, XP & badges",
        how: "Sequential modules break an open-ended dream into sessions with tasks, reflections, quizzes and rewards. There is always exactly one next step, and it is small.",
      },
      {
        surface: "Altitut Game: quests, coins & daily rewards",
        how: "\u201cWeek 1: Build Your Startup\u201d turns real onboarding into ten rewarded tasks with coins, levels, pets and leaderboards. On the days willpower is gone, the loop carries you.",
      },
    ],
    reframe:
      "You do not need more motivation. You need a next step small enough to take on your worst day.",
    images: [
      { frame: "the-quiet-quit-failure", caption: "Momentum, coming apart quietly at the edges." },
      { frame: "the-quiet-quit-system", caption: "A calendar with the gap you did not notice." },
      { frame: "the-quiet-quit-diagnosis", caption: "The fade, plotted honestly." },
    ],
  },
];

export const FAILURE_SLUGS = FAILURES.map((failure) => failure.slug);

export function getFailure(slug: string): Failure | undefined {
  return FAILURES.find((failure) => failure.slug === slug);
}

export function getFailureNeighbours(slug: string): {
  previous: Failure;
  next: Failure;
} {
  const index = FAILURES.findIndex((failure) => failure.slug === slug);
  const length = FAILURES.length;
  return {
    previous: FAILURES[(index - 1 + length) % length],
    next: FAILURES[(index + 1) % length],
  };
}
